version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      POSTGRES_DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}"
      # MONGODB_DATABASE_URL: "mongodb://mongouser:mongopass@mongo_db:27017/spreadsheetcontent?authSource=admin&replicaSet=rs0"
      MONGODB_DATABASE_URL: "mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo_db:27017/${MONGO_DATABASE}?authSource=admin&replicaSet=rs0"
    depends_on:
      - postgres_db
      - mongo_db
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: >
      sh -c "
        sleep 5
        npx prisma migrate dev --schema=./prisma/postgresql/schema.prisma
        npx prisma db push --schema=./prisma/mongodb/schema.prisma
        npm run dev
      "
    networks:
      - app-network

  # PostgreSQL Database
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app-network

  # MongoDB Database
  mongo_db:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./mongo-keyfile:/tmp/mongo-keyfile-host:ro
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    entrypoint:
      - "mongod"
      - "--replSet"
      - "rs0"
      - "--bind_ip_all"
      - "--keyFile"
      - "/tmp/mongo-keyfile-host"
    command: []
    restart: always
    networks:
      - app-network

volumes:
  mongodata:
  pgdata:

networks:
  app-network:
    driver: bridge
